# https://stackoverflow.com/a/2481326
CXX=g++
CC=gcc
RM=rm -f
CXXFLAGS=-fopenmp
CFLAGS=-fopenmp
empty:=

CPPSRCS=$(wildcard *_omp.cpp)
CPPOBJS=$(subst .cpp,.o,$(CPPSRCS))
CPPEXES=$(subst .cpp,$(empty),$(CPPSRCS))

CSRCS=$(wildcard *_omp.c)
COBJS=$(subst .c,.o,$(CSRCS))
CEXES=$(subst .c,$(empty),$(CSRCS))

all: $(CPPEXES) $(CEXES)

clean:
	$(RM) $(CPPOBJS) $(CPPEXES) $(COBJS) $(CEXES)

distclean: clean
	$(RM) *~
